name: Contribution template
description: Template for an extensive description, to enable other contributors to discuss about and implement a feature of the patcher.
labels: ["status: novel issue"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
  - type: textarea
    id: action
    attributes:
      label: Course of Action
  - type: textarea
    id: test
    attributes:
      label: Test Plan
